Controllers/CariController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcOnlineTicariOtomasyon.Models.Siniflar;

namespace MvcOnlineTicariOtomasyon.Controllers 
{
    public class CariController : Controller
    {
        Context context = new Context();
        // GET: Cari 
        public ActionResult Index() 
        {
            var cariler = context.Carilers.ToList();
             
            return View(cariler);
        }
        
        [HttpGet]
        public ActionResult YeniCariEkle()
        {
            return View();
        }

        [HttpPost]
        public ActionResult YeniCariEkle(Cariler c)
        {
            if (!ModelState.IsValid)
            {
                return View("YeniCariEkle");
            }
            context.Carilers.Add(c);
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult CariSil(int id)
        {
            var cari = context.Carilers.Find(id);
            context.Carilers.Remove(cari);
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult CariGuncelle(int id)
        {
            var cari = context.Carilers.Find(id);
            return View(cari);
        }

        [HttpPost]
        public ActionResult CariGuncelle(Cariler c)
        {
            if (!ModelState.IsValid)
            {
                return View("CariGuncelle");
            }
            var cari = context.Carilers.Find(c.CariId);
            cari.CariAd = c.CariAd;
            cari.CariSoyad = c.CariSoyad;
            cari.CariSehir = c.CariSehir;
            cari.CariMail = c.CariMail;
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult CariDetay(int id)
        {
            var cariDetay = context.SatisHarekets.Where(x => x.CariId == id).ToList();
            var cari = context.Carilers.Where(x => x.CariId == id).Select(y => y.CariAd + " " + y.CariSoyad).FirstOrDefault();
            ViewBag.cari = cari;

            return View(cariDetay);
        }
    }
}

Controllers/FaturaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcOnlineTicariOtomasyon.Models.Siniflar;

namespace MvcOnlineTicariOtomasyon.Controllers
{
    public class FaturaController : Controller
    {
        Context context = new Context();
        // GET: Fatura
        public ActionResult Index()
        {
            var faturalar = context.Faturas.ToList();
            return View(faturalar);
        }

        [HttpGet]
        public ActionResult YeniFaturaEkle()
        {
            return View();
        }

        [HttpPost]
        public ActionResult YeniFaturaEkle(Fatura f)
        {
            if (ModelState.IsValid == true)
            {
                context.Faturas.Add(f);
                context.SaveChanges();
                return RedirectToAction("Index");
            }

            return View("YeniFaturaEkle");
            
        }

        [HttpGet]
        public ActionResult FaturaGuncelle(int id)
        {
            var fatura = context.Faturas.Find(id);
            return View(fatura);
        }

        [HttpPost]
        public ActionResult FaturaGuncelle(Fatura f)
        {
            if (ModelState.IsValid == true)
            {
            var fatura = context.Faturas.Find(f.FaturaId);
            fatura.FaturaSiraNo = f.FaturaSiraNo;
            fatura.Tarih = f.Tarih;
            fatura.Saat = f.Saat;
            fatura.TeslimEden = f.TeslimEden;
            fatura.TeslimAlan = f.TeslimAlan;
            fatura.VergiDairesi = f.VergiDairesi;
            fatura.ToplamTutar = f.ToplamTutar;
            context.SaveChanges();
            return RedirectToAction("Index");
            }

            return View("FaturaGuncelle");

        }
        public ActionResult FaturaDetay(int id)
        {
            var detay = context.FaturaKalems.Where(x => x.FaturaId == id).ToList();
            ViewBag.detay = detay;
            return View(detay);
        }

        [HttpGet]
        public ActionResult YeniKalemEkle()
        {
            return View();
        }

        [HttpPost]
        public ActionResult YeniKalemEkle(FaturaKalem k)
        {
            context.FaturaKalems.Add(k);
            context.SaveChanges();
            return RedirectToAction("Index/FaturaDetay");
        }

        public ActionResult DinamikFaturalar()
        {
            DinamikFaturalarClass dinamikFatura = new DinamikFaturalarClass();

            dinamikFatura.fatura = context.Faturas.ToList();
            dinamikFatura.faturaKalem = context.FaturaKalems.ToList();

            return View(dinamikFatura);
        }

        public ActionResult DinamikFaturaEkle(string FaturaSiraNo, DateTime Tarih, string VergiDairesi, string Saat,
                                                string TeslimAlan, string TeslimEden, string ToplamTutar, FaturaKalem[] kalemler)
        {
            Fatura fatura = new Fatura();
            fatura.FaturaSiraNo = FaturaSiraNo;
            fatura.Tarih = Tarih;
            fatura.TeslimAlan = TeslimAlan;
            fatura.TeslimEden = TeslimEden;
            fatura.VergiDairesi = VergiDairesi;
            fatura.ToplamTutar = decimal.Parse(ToplamTutar);
            fatura.Saat = Saat;
            context.Faturas.Add(fatura);
            

            foreach (var x in kalemler)
            {
                FaturaKalem faturaKalem = new FaturaKalem();
                faturaKalem.Aciklama = x.Aciklama;
                faturaKalem.BirimFiyat = x.BirimFiyat;
                faturaKalem.Miktar = x.Miktar;
                faturaKalem.Tutar = x.Tutar;
                faturaKalem.Tutar = x.Miktar * x.BirimFiyat;


                context.FaturaKalems.Add(faturaKalem);



            }
            context.SaveChanges();
            return Json("İşlem Başarılı", JsonRequestBehavior.AllowGet);

        }

    }
}

Controllers/SatisController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcOnlineTicariOtomasyon.Models.Siniflar;

namespace MvcOnlineTicariOtomasyon.Controllers
{
    public class SatisController : Controller
    {
        Context context = new Context();
        // GET: Satis
        public ActionResult Index()
        {
            var satislar = context.SatisHarekets.ToList();
            return View(satislar);
        }

        [HttpGet]
        public ActionResult YeniSatisEkle()
        {
            List<SelectListItem> deger = (from x in context.Uruns.ToList()
                                          select new SelectListItem
                                          {
                                              Text = x.UrunAd,
                                              Value = x.UrunID.ToString()
                                          }).ToList();
            ViewBag.deger1 = deger;

            List<SelectListItem> deger2 = (from x in context.Carilers.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.CariAd + " " + x.CariSoyad,
                                               Value = x.CariId.ToString()
                                           }).ToList();
            ViewBag.deger2 = deger2;

            List<SelectListItem> deger3 = (from x in context.Personels.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.PersonelAd + " " + x.PersonelSoyad,
                                               Value = x.PersonelId.ToString()
                                           }).ToList();
            ViewBag.deger3 = deger3;
            return View();

            
        }

        [HttpPost]
        public ActionResult YeniSatisEkle(SatisHareket s)
        {
            if(ModelState.IsValid == true)
            {
                    s.Tarih = DateTime.Parse(DateTime.Now.ToShortDateString());
                    context.SatisHarekets.Add(s);
                    
                    context.SaveChanges();
                    return RedirectToAction("Index");
            }

            return View("YeniSatisEkle");
            
        }

        [HttpGet]
        public ActionResult SatisGuncelle(int id)
        {
            var s = context.SatisHarekets.Where(x => x.SatisId == id).Select(y => y.SatisId).FirstOrDefault();
            ViewBag.s = s;

            List<SelectListItem> deger = (from x in context.Uruns.ToList()
                                          select new SelectListItem
                                          {
                                              Text = x.UrunAd,
                                              Value = x.UrunID.ToString()
                                          }).ToList();
            ViewBag.deger1 = deger;

            List<SelectListItem> deger2 = (from x in context.Carilers.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.CariAd + " " + x.CariSoyad,
                                               Value = x.CariId.ToString()
                                           }).ToList();
            ViewBag.deger2 = deger2;

            List<SelectListItem> deger3 = (from x in context.Personels.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.PersonelAd + " " + x.PersonelSoyad,
                                               Value = x.PersonelId.ToString()
                                           }).ToList();
            ViewBag.deger3 = deger3;
            var satis = context.SatisHarekets.Find(id);
            return View(satis);
        }

        [HttpPost]
        public ActionResult SatisGuncelle(SatisHareket s)
        {
            if (ModelState.IsValid == true)
            {
            var satis = context.SatisHarekets.Find(s.SatisId);
            satis.UrunID = s.UrunID;
            satis.CariId = s.CariId;
            satis.Adet = s.Adet;
            satis.BirimFiyat = s.BirimFiyat;
            satis.PersonelId = s.PersonelId;
            satis.Tutar = s.Tutar;

            context.SaveChanges();
            return RedirectToAction("Index");
            }
            return View("SatisGuncelle");


        }

        public ActionResult SatisDetay(int id)
        {
            var satis = context.SatisHarekets.Where(x => x.SatisId == id).ToList();
            return View(satis);
        }
    }
}

Controllers/UrunController.cs
using System;
using System.Collections.Generic;
using System.Linq;
//using System.Web;
using System.Web.Mvc;
using MvcOnlineTicariOtomasyon.Models.Siniflar;

namespace MvcOnlineTicariOtomasyon.Controllers
{
    public class UrunController : Controller
    {
        Context context = new Context();
        // GET: Urun
        public ActionResult Index(string p)
        {
            var urunler = from x in context.Uruns select x;
            if (!string.IsNullOrEmpty(p))
            {
                urunler = urunler.Where(y => y.UrunAd.Contains(p));
            }
            
            return View(urunler.ToList());
        }

        [HttpGet]
        public ActionResult YeniUrunEkle()
        {

            List<SelectListItem> deger = (from x in context.Kategoris.ToList()
                                          select new SelectListItem
                                          {
                                              Text = x.KategoriAd,
                                              Value = x.KategoryId.ToString()
                                          }).ToList();

            ViewBag.deger1 = deger;
            return View();
        }

        [HttpPost]
        public ActionResult YeniUrunEkle(Urun u)
        {
            if (ModelState.IsValid == true)
            {
                context.Uruns.Add(u);
                context.SaveChanges();
                return RedirectToAction("Index");
            }
            
            return View("YeniUrunEkle"); 
            

        }

        public ActionResult UrunSil(int id)
        {
            var deger = context.Uruns.Find(id);
            context.Uruns.Remove(deger);
            deger.Durum = false;
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        
        public ActionResult UrunGetir(int id)
        {
            //if (!ModelState.IsValid)
            //{
            //    return View("UrunGetir");
            //}
            //List<SelectListItem> deger = (from x in context.Kategoris.ToList()
            //                              select new SelectListItem
            //                              {
            //                                  Text = x.KategoriAd,
            //                                  Value = x.KategoryId.ToString()
            //                              }).ToList();
            //ViewBag.deger1 = deger;
            var urundeger = context.Uruns.Find(id);

            return View("UrunGetir", urundeger);  
        }


        public ActionResult UrunGuncelle(Urun u)
        {
            if (ModelState.IsValid)
            {
                Urun urun = context.Uruns.Find(u.UrunID);

                urun.Stok = u.Stok;
                urun.UrunAd = u.UrunAd;
                urun.Marka = u.Marka;
                urun.AlisFiyati = u.AlisFiyati;
                urun.SatisFiyati = u.SatisFiyati;

                urun.UrunGorsel = u.UrunGorsel;
                urun.Durum = u.Durum;
                urun.KategoryId = u.KategoryId;

                context.SaveChanges();

                return RedirectToAction("Index");
            }
            return View("UrunGetir");

            
        }

        public ActionResult UrunListesi()
        {
            var liste = context.Uruns.ToList();
            return View(liste);
        }

        [HttpGet]
        public ActionResult SatisYap(int id)
        {
            var urun= context.Uruns.Find(id);
            ViewBag.deger1 = urun.UrunID;

            List<SelectListItem> deger2 = (from x in context.Carilers.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.CariAd + " " + x.CariSoyad,
                                               Value = x.CariId.ToString()
                                           }).ToList();
            ViewBag.deger2 = deger2;

            List<SelectListItem> deger3 = (from x in context.Personels.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.PersonelAd + " " + x.PersonelSoyad,
                                               Value = x.PersonelId.ToString()
                                           }).ToList();
            ViewBag.deger3 = deger3;

            ViewBag.BirimFiyat = urun.SatisFiyati;
            return View();
        }

        [HttpPost]
        public ActionResult SatisYap(SatisHareket s)
        {
            var urun = context.Uruns.Find(s.UrunID);
            s.Tarih = DateTime.Parse(DateTime.Now.ToShortDateString());
            context.SatisHarekets.Add(s);
            
            context.SaveChanges();
            return RedirectToAction("Index");
            
        }


    }
}

Views/Shared/_AdminLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Ticari Otomasyon</title>
    <link href="~/Themes/web/dist/css/styles.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/Themes/thumber/fonts/flaticon/font/flaticon.css">


    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/js/all.min.js" crossorigin="anonymous"></script>

</head>
<body>
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <a class="navbar-brand" href="/Kategori/Index">Ticari Otomasyon</a><button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#">
            <i class="fas fa-bars"></i>
        </button><!-- Navbar Search-->
        <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
            <div class="input-group">
                <input class="form-control" type="text" placeholder="Ara..." aria-label="Search" aria-describedby="basic-addon2" />
                <div class="input-group-append">
                    <button class="btn btn-primary" type="button"><i class="fas fa-search"></i></button>
                </div>
            </div>
        </form>
        <!-- Navbar-->
        <ul class="navbar-nav ml-auto ml-md-0">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                    <a class="dropdown-item" href="/Admin/Index">Hesap</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="/Admin/LogOut">Çıkış</a>
                </div>
            </li>
        </ul>
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <div class="sb-sidenav-menu-heading">İşlemler</div>
                        <a class="nav-link" href="/Admin/Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                            Profilim
                        </a>
                        <a class="nav-link" href="/Kategori/Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                            Kategoriler
                        </a>
                        <a class="nav-link" href="/Urun/Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-hourglass"></i></div>
                            Ürünler
                        </a>
                        <a class="nav-link" href="/Departman/Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-sitemap"></i></div>
                            Departmanlar
                        </a>
                        <a class="nav-link" href="/Cari/Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-user"></i></div>
                            Cariler
                        </a>
                        <a class="nav-link" href="/Personel/Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-users"></i></div>
                            Personeler
                        </a>

                        <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav"><a class="nav-link" href="layout-static.html">Static Navigation</a><a class="nav-link" href="layout-sidenav-light.html">Light Sidenav</a></nav>
                        </div>
                        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="false" aria-controls="collapsePages">
                            <div class="sb-nav-link-icon"><i class="fas fa-lock"></i></div>
                            Grafikler
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="collapsePages" aria-labelledby="headingTwo" data-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages">
                                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#pagesCollapseAuth" aria-expanded="false" aria-controls="pagesCollapseAuth">
                                    Grafik Türleri
                                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                </a>
                                <div class="collapse" id="pagesCollapseAuth" aria-labelledby="headingOne" data-parent="#sidenavAccordionPages">
                                    <nav class="sb-sidenav-menu-nested nav">
                                        <a class="nav-link" href="/Grafik/Index5">Pie Grafik</a>
                                        <a class="nav-link" href="/Grafik/Index6">Line Grafik</a>
                                        <a class="nav-link" href="/Grafik/Index7">Column Grafik</a>
                                    </nav>
                                </div>
                                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#pagesCollapseError" aria-expanded="false" aria-controls="pagesCollapseError">
                                    Hata Sayfaları
                                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                </a>
                                <div class="collapse" id="pagesCollapseError" aria-labelledby="headingOne" data-parent="#sidenavAccordionPages">
                                    <nav class="sb-sidenav-menu-nested nav"><a class="nav-link" href="401.html">401 Page</a><a class="nav-link" href="404.html">404 Page</a><a class="nav-link" href="500.html">500 Page</a></nav>
                                </div>
                            </nav>
                        </div>
                        <div class="sb-sidenav-menu-heading">Rapor & Fatura</div>
                        <a class="nav-link" href="/Satis/Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-list-ol"></i></div>
                            Satışlar
                        </a>
                        <a class="nav-link" href="/Fatura/Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-list-ol"></i></div>
                            Faturalar
                        </a>
                        <a class="nav-link" href="/Fatura/DinamikFaturalar">
                            <div class="sb-nav-link-icon"><i class="fas fa-list-ol"></i></div>
                            Dinamik Faturalar
                        </a>
                        <a class="nav-link" href="/Kargo/Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-list-ol"></i></div>
                            Kargolar
                        </a>
                        <a class="nav-link" href="/Urun/UrunListesi">
                            <div class="sb-nav-link-icon"><i class="fas fa-print"></i></div>
                            PDF & EXCELL
                        </a>
                        <a class="nav-link" href="/Istatistik/Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-signal"></i></div>
                            İstatistikler
                        </a>
                        <a class="nav-link" href="/Yapilacaklar/Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-signal"></i></div>
                            Yapilacaklar Listesi
                        </a>
                        <a class="nav-link" href="/Galeri/Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-camera-retro"></i></div>
                            Galeri
                        </a>
                        @if (User.IsInRole("A"))
                        {
                            <a class="nav-link" href="/UrunDetay/Index">
                                <div class="sb-nav-link-icon"><i class="fas fa-calculator"></i></div>
                                Ürün Detay
                            </a>
                        }
                        <a class="nav-link" href="/Istatistik/Tablolar">
                            <div class="sb-nav-link-icon"><i class="fas fa-signal"></i></div>
                            Tablolar
                        </a>
                        <a class="nav-link" href="/Personel/PersonelListe">
                            <div class="sb-nav-link-icon"><i class="fas fa-signal"></i></div>
                            Personel Ayrıntılı
                        </a>
                    </div>
                </div>
                @*<div class="sb-sidenav-footer">
                    <div class="small">Giriş Yaptınız:</div>
                    Ticari Otomasyon
                </div>*@
            </nav>
        </div>
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid">
                    @RenderBody()
                </div>
            </main>
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; Your Website 2019</div>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="~/Themes/web/dist/js/scripts.js"></script>
</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Faturalar 2</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @*@Html.ActionLink("Anasayfa", "Index", "Fatura")*@
                @Html.ActionLink("Anasayfa", "Index", "Fatura", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Kategori", "Index", "Kategori")</li>
                    <li>@Html.ActionLink("Urunler", "Index", "Urun")</li>
                    <li>@Html.ActionLink("Satışlar", "Index", "Satis")</li>
                    <li>@Html.ActionLink("Cariler", "Index", "Cari")</li>
                    <li>@Html.ActionLink("Personeller", "Index", "Personel")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />

    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>