Models/Siniflar/KargoTakip.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace MvcOnlineTicariOtomasyon.Models.Siniflar
{
    public class KargoTakip
    {
        [Key]
        public int KargoTakipId { get; set; }

        [Column(TypeName = "VarChar")]
        [StringLength(20)]
        public string KargoTakipKodu { get; set; }

        [StringLength(250)]
        [Column(TypeName = "VarChar")]
        public string Aciklama { get; set; }
        public DateTime Tarih { get; set; }
    }
}

Controllers/CariPanelController.cs
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using MvcOnlineTicariOtomasyon.Models.Siniflar;


namespace MvcOnlineTicariOtomasyon.Controllers
{
    public class CariPanelController : Controller
    {
        Context context = new Context();

        // GET: CariPanel

        [Authorize]
        public ActionResult Index()
        {
            var mail = (string)Session["CariMail"];
            var degerler = context.Carilers.FirstOrDefault(x => x.CariMail == mail);

            var cariId = context.Carilers.Where(x => x.CariMail == mail).Select(y => y.CariId).FirstOrDefault();
            var carix = context.SatisHarekets.Find(cariId);

            var toplamAlis = 0;
            decimal toplamTutar = 0;
            var toplamUrunSayisi = 0;

            if (carix != null)
            {
                         toplamAlis = context.SatisHarekets.Count(x => x.CariId == cariId);
                         toplamTutar = context.SatisHarekets.Where(x => x.CariId == cariId).Sum(y => y.Tutar);
                         toplamUrunSayisi = context.SatisHarekets.Where(x => x.CariId == cariId).Sum(y => y.Adet);
                
                        
            }
            else
            {
                 toplamAlis = 0;
                 toplamTutar = 0;
                 toplamUrunSayisi = 0;
            }

                 ViewBag.toplamUrunSayisi = toplamUrunSayisi;
                 ViewBag.toplamSatisTutari = toplamTutar;
                 ViewBag.toplamAlis = toplamAlis;



            var mesajlar = context.Mesajlars.Where(x => x.Alici == mail.ToString()).ToList();

            dynamic model = new ExpandoObject();
            model.degerler = degerler;
            model.mesajlar = mesajlar;

            return View(model);

        }

        [Authorize]
        public ActionResult SiparisGoster()
        {
            var mail = (string)Session["CariMail"];
            var cariId = context.Carilers.Where(x => x.CariMail == mail.ToString()).Select(y => y.CariId).FirstOrDefault();
            //var cari = context.Carilers.Find(cariId);
            var satislar = context.SatisHarekets.Where(x => x.CariId == cariId).ToList();

            return View(satislar);
        }

        [Authorize]
        public ActionResult GelenMesajlar()
        {
            var mail = (string)Session["CariMail"];
            var degerler = context.Mesajlars.Where(x => x.Alici == mail).ToList();
            var mesajSayisi = context.Mesajlars.Where(x => x.Alici == mail).Count();
            ViewBag.mesajSayisi = mesajSayisi;
            var gonderilenMesajSayisi = context.Mesajlars.Where(x => x.Gonderen == mail).Count();
            ViewBag.gonderilenMesajSayisi = gonderilenMesajSayisi;

            return View(degerler);
        }

        [Authorize]
        public ActionResult GonderilenMesajlar()
        {
            var mail = (string)Session["CariMail"];
            var degerler = context.Mesajlars.Where(x => x.Gonderen == mail).ToList();
            var mesajSayisi = context.Mesajlars.Where(x => x.Alici == mail).Count();
            ViewBag.mesajSayisi = mesajSayisi;
            var gonderilenMesajSayisi = context.Mesajlars.Where(x => x.Gonderen == mail).Count();
            ViewBag.gonderilenMesajSayisi = gonderilenMesajSayisi;

            return View(degerler);

        }

        [Authorize]
        public ActionResult MesajDetay(int id)
        {
            var mail = (string)Session["CariMail"];
            var degerler = context.Mesajlars.Where(x => x.MesajId == id).ToList().FirstOrDefault();
            var mesajSayisi = context.Mesajlars.Where(x => x.Alici == mail).Count();
            ViewBag.mesajSayisi = mesajSayisi;
            var gonderilenMesajSayisi = context.Mesajlars.Where(x => x.Gonderen == mail).Count();
            ViewBag.gonderilenMesajSayisi = gonderilenMesajSayisi;

            return View(degerler);
        }

        [Authorize]
        [HttpGet]
        public ActionResult YeniMesaj()
        {
            var mail = (string)Session["CariMail"];
            var mesajSayisi = context.Mesajlars.Where(x => x.Alici == mail).Count();
            ViewBag.mesajSayisi = mesajSayisi;
            var gonderilenMesajSayisi = context.Mesajlars.Where(x => x.Gonderen == mail).Count();
            ViewBag.gonderilenMesajSayisi = gonderilenMesajSayisi;
            return View();
        }

        [Authorize]
        [HttpPost]
        public ActionResult YeniMesaj(Mesajlar mesaj)
        {
            var mail = (string)Session["CariMail"];
            mesaj.Tarih = DateTime.Parse(DateTime.Now.ToShortDateString());
            mesaj.Gonderen = mail;
            context.Mesajlars.Add(mesaj);
            context.SaveChanges();
            return RedirectToAction("GelenMesajlar");
        }

        [Authorize]
        public ActionResult KargoTakip(string p)
        {
            dynamic model = new ExpandoObject();
            model.kargoDetays = context.KargoDetays;
            model.kargoTakips = context.KargoTakips;

            var mail = (string)Session["CariMail"];
            var kargolar = from x in context.KargoDetays select x;

            if (!string.IsNullOrEmpty(p))
            {
                kargolar = kargolar.Where(y => y.KargoTakipKodu.Contains(p));
            }
            var cariAd = context.Carilers.Where(x => x.CariMail == mail.ToString()).Select(y => y.CariAd + " " + y.CariSoyad).FirstOrDefault();
            var kargoTakipKodu = kargolar.Select(x => x.KargoTakipKodu).FirstOrDefault();
            model.kargoDetays = kargolar.Where(x => x.AliciCari == cariAd).ToList();
            model.kargoTakips = context.KargoTakips.Where(x => x.KargoTakipKodu == kargoTakipKodu).ToList();
            ViewBag.p = p;

            return View(model);

        }

        public ActionResult LogOut()
        {
            FormsAuthentication.SignOut();
            Session.Abandon();
            return RedirectToAction("Index", "Login");
        }
        public PartialViewResult DuyuruPartial()
        {
            var mail = (string)Session["CariMail"];
            var mesajlar = context.Mesajlars.Where(x => x.Gonderen == "ADMIN").ToList();

            return PartialView(mesajlar);
        }
        public PartialViewResult BilgiGuncelle()
        {
            var mail = (string)Session["CariMail"];
            var cariler = context.Carilers.Where(x => x.CariMail == mail).FirstOrDefault();
            return PartialView("BilgiGuncelle", cariler);
        }

        public ActionResult BilgiGuncelle2(Cariler cari)
        {
            var mail = (string)Session["CariMail"];
            var cari1 = context.Carilers.Where(x => x.CariMail == mail).FirstOrDefault();
            cari1.CariAd = cari.CariAd;
            cari1.CariSoyad = cari.CariSoyad;
            cari1.CariSehir = cari.CariSehir;
            cari1.CariMail = cari.CariMail;
            cari1.CariSifre = cari.CariSifre;
            context.SaveChanges();
            

            return RedirectToAction("Index");
        }


    }
    }

Views/CariPanel/BilgiGuncelle.cshtml
@model MvcOnlineTicariOtomasyon.Models.Siniflar.Cariler

@using(Html.BeginForm("BilgiGuncelle2", "CariPanel", FormMethod.Post))
{ 
<form class="form-horizontal">
    <div class="form-group row">
        <label for="inputName" class="col-sm-2 col-form-label">Ad</label>
        <div class="col-sm-10">
            @Html.TextBoxFor(x=>x.CariAd, new { @class = "form-control"})
        </div>
    </div>
    <div class="form-group row">
        <label for="inputEmail" class="col-sm-2 col-form-label">Soyad</label>
        <div class="col-sm-10">
            @Html.TextBoxFor(x => x.CariSoyad, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group row">
        <label for="inputName2" class="col-sm-2 col-form-label">Şehir</label>
        <div class="col-sm-10">
            @Html.TextBoxFor(x => x.CariSehir, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group row">
        <label for="inputExperience" class="col-sm-2 col-form-label">E-Mail</label>
        <div class="col-sm-10">
            @Html.TextBoxFor(x => x.CariMail, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group row">
        <label for="inputSkills" class="col-sm-2 col-form-label">Şifre</label>
        <div class="col-sm-10">
            @Html.TextBoxFor(x => x.CariSifre, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group row">
        <div class="offset-sm-2 col-sm-10">
            <button type="submit" class="btn btn-danger">Submit</button>
        </div>
    </div>
</form>
}

Views/CariPanel/Index.cshtml
@using MvcOnlineTicariOtomasyon.Models.Siniflar
@model dynamic
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_CariLayout.cshtml";
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>AdminLTE 3 | User Profile</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/Themes/AdminLTE-3.0.4/plugins/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/Themes/AdminLTE-3.0.4/dist/css/adminlte.min.css">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition sidebar-mini">
    <div class="wrapper">

            
            <section class="content">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-3">

                            <!-- Profile Image -->
                            <div class="card card-primary card-outline">
                                <div class="card-body box-profile">
                                    <div class="text-center">
                                        <img class="profile-user-img img-fluid img-circle"
                                             src="~/Themes/AdminLTE-3.0.4/dist/img/user4-128x128.jpg"
                                             alt="User profile picture">
                                    </div>

                                    <h3 class="profile-username text-center">@Model.degerler.CariAd @Model.degerler.CariSoyad</h3>

                                    <p class="text-muted text-center">@Model.degerler.CariMail</p>

                                    <ul class="list-group list-group-unbordered mb-3">
                                        <li class="list-group-item">
                                            <b>Toplam Alış Sayısı</b> <a class="float-right">@ViewBag.toplamAlis</a>
                                        </li>
                                        <li class="list-group-item">
                                            <b>Toplam Maliyet Tutarı</b> <a class="float-right">@ViewBag.toplamSatisTutari ₺</a>
                                        </li>
                                        <li class="list-group-item">
                                            <b>Alınan Toplam Ürün Sayısı</b> <a class="float-right">@ViewBag.toplamUrunSayisi</a>
                                        </li>
                                    </ul>

                                    <a href="/CariPanel/KargoTakip" class="btn btn-primary btn-block"><b>KargoTakip</b></a>
                                </div>
                                <!-- /.card-body -->
                            </div>
                            <!-- /.card -->
                            <!-- About Me Box -->
                            <div class="card card-primary">
                                <div class="card-header">
                                    <h3 class="card-title">
                                        Hakkımda
                                    </h3>
                                </div>
                                <!-- /.card-header -->
                                <div class="card-body">
                                    <strong><i class="fas fa-book mr-1"></i> Meslek</strong>

                                    <p class="text-muted">
                                        Kişinin Mesleği Yazılacak
                                    </p>

                                    <hr>

                                    <strong><i class="fas fa-map-marker-alt mr-1"></i> Şehir</strong>

                                    <p class="text-muted">@Model.degerler.CariSehir</p>

                                    <hr>

                                    <strong><i class="fas fa-pencil-alt mr-1"></i> Telefon No</strong>

                                    <p class="text-muted">(+90) ___ ___ __ __</p>

                                    <hr>

                                    <strong><i class="far fa-file-alt mr-1"></i> Notlar</strong>

                                    <p class="text-muted">Kişi Buraya Not Yazabilir.</p>
                                </div>
                                <!-- /.card-body -->
                            </div>
                            <!-- /.card -->
                        </div>
                        <!-- /.col -->
                        <div class="col-md-9">
                            <div class="card">
                                <div class="card-header p-2">
                                    <ul class="nav nav-pills">
                                        <li class="nav-item"><a class="nav-link active" href="#activity" data-toggle="tab">Mesajlar</a></li>
                                        <li class="nav-item"><a class="nav-link" href="#timeline" data-toggle="tab">Duyurular</a></li>
                                        <li class="nav-item"><a class="nav-link" href="#settings" data-toggle="tab">Hesap</a></li>
                                    </ul>
                                </div><!-- /.card-header -->
                                <div class="card-body">
                                    <div class="tab-content">
                                        <div class="active tab-pane" id="activity">
                                            <!-- Post -->
                                            @foreach (Mesajlar m in Model.mesajlar)
                                            {
                                                <div class="post">
                                                    <div class="user-block">
                                                        <img class="img-circle img-bordered-sm" src="~/Themes/AdminLTE-3.0.4/dist/img/user1-128x128.jpg" alt="user image">
                                                        <span class="username">
                                                            <a href="#">@m.Gonderen</a>
                                                            <a href="#" class="float-right btn-tool"><i class="fas fa-times"></i></a>
                                                        </span>
                                                        <span class="description">@m.Tarih Tarihinde Gönderildi</span>
                                                    </div>
                                                    <!-- /.user-block -->
                                                    <p>
                                                        @m.MesajIcerik
                                                    </p>
                                                    <p>
                                                        <a href="#" class="link-black text-sm mr-2"><i class="fas fa-share mr-1"></i> İlet</a>
                                                        <a href="#" class="link-black text-sm"><i class="far fa-thumbs-up mr-1"></i> Okundu Olarak İşaretle</a>
                                                    </p>
                                                </div>
                                            }

   
                                        </div>


                                        @Html.Action("DuyuruPartial", "CariPanel")

                                        <div class="tab-pane" id="settings">


                                            @Html.Action("BilgiGuncelle", "CariPanel")

                                        </div>
                                        <!-- /.tab-pane -->
                                    </div>
                                    <!-- /.tab-content -->
                                </div><!-- /.card-body -->
                            </div>
                            <!-- /.nav-tabs-custom -->
                        </div>
                        <!-- /.col -->
                    </div>
                    <!-- /.row -->
                </div><!-- /.container-fluid -->
            </section>
           
       
    </div>
    <!-- ./wrapper -->
    <!-- jQuery -->
    <script src="~/Themes/AdminLTE-3.0.4/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="~/Themes/AdminLTE-3.0.4/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/Themes/AdminLTE-3.0.4/dist/js/adminlte.min.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="~/Themes/AdminLTE-3.0.4/dist/js/demo.js"></script>
</body>
</html>

Views/CariPanel/KargoTakip.cshtml
@using MvcOnlineTicariOtomasyon.Models.Siniflar
@model dynamic

@{
    ViewBag.Title = "KargoTakip";
    Layout = "~/Views/Shared/_CariLayout.cshtml";
}
<br />
<h3>Kargo Özeti</h3>
<br />

@using (Html.BeginForm("KargoTakip", "CariPanel", FormMethod.Get))
{
    <p>
        Kargo Takip Kodu : @Html.TextBox("p")
        <input type="submit" value="Ara"/>
    </p>

}
<br />
<table class="table table-bordered" , style="margin-top:20px">
    <tr>
        <td><h5>Gönderen</h5></td>
        <td><h5>Alıcı</h5></td>
        <td><h5>Açıklama</h5></td>
        <td><h5>Tarih</h5></td>
        <td><h5>Takip Kodu</h5></td>
        @if (!string.IsNullOrEmpty(ViewBag.p))
        {
            <td><h5>Detay</h5></td>

        }
    </tr>
    @foreach (KargoDetay d in Model.kargoDetays)
    {
<tr>
    <td>@d.GonderenPersonel</td>
    <td>@d.AliciCari</td>
    <td>@d.Aciklama</td>
    <td>@d.Tarih</td>
    <td>@d.KargoTakipKodu</td>
    @{
        if (!string.IsNullOrEmpty(ViewBag.p))
        {
            <td>
                <button class="btn btn-dark" style="color:white;" data-toggle="modal" data-target="#Modal1">Kargo</button>
            </td>
        }
    }

</tr>
    }


</table>
<br />
<h3>Kargonuzun durumunu sorgulayabilmek için kargo takip kodunuzu arama yerine giriniz.</h3>

<div class="modal" id="Modal1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h2 class="modal-title">
                    PopUp Dialog Ekranı
                </h2>
            </div>
            <div class="modal-body">
                <table class="table table-hover">
                    <tr>
                        <td>Açıklama</td>
                        <td>Tarih</td>

                    </tr>
                    @foreach (KargoTakip f in Model.kargoTakips)
                    {
                        <tr>
                            <td>@f.Aciklama</td>
                            <td>@f.Tarih</td>
                            @*<td>@f.Saat</td>
                                <td>@f.ToplamTutar</td>*@
                        </tr>
                    }
                </table>
                <button type="button" data-dismiss="modal" class="btn btn-danger">Kapat</button>

            </div>

        </div>
    </div>
</div>

Views/CariPanel/SiparisGoster.cshtml
@using MvcOnlineTicariOtomasyon.Models.Siniflar
@model List<SatisHareket>
@{
    ViewBag.Title = "SiparisGoster";
    Layout = "~/Views/Shared/_CariLayout.cshtml";
}
<br />
<h2>Siparişleriniz</h2>
<br />

<table class="table table-bordered">
    <tr>
        <td>Tarih</td>
        <td>Adet</td>
        <td>Birim Fiyat</td>
        <td>Toplam Tutar</td>
        <td>Personel</td>
        <td>Urun</td>

    </tr>
    @foreach (var s in Model)
    {
        <tr>
            <td>@s.Tarih</td>
            <td>@s.Adet</td>
            <td>@s.BirimFiyat</td>
            <td>@s.Tutar</td>
            <td>@s.Personel.PersonelAd @s.Personel.PersonelSoyad</td>
            <td>@s.Urun.UrunAd</td>

        </tr>
    }
</table>

Views/CariPanel/YeniMesaj.cshtml
@model MvcOnlineTicariOtomasyon.Models.Siniflar.Mesajlar
@{
    ViewBag.Title = "YeniMesaj";
    Layout = "~/Views/Shared/_CariLayout.cshtml";
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>AdminLTE 3 | Compose Message</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/Themes/AdminLTE-3.0.4/plugins/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/Themes/AdminLTE-3.0.4/dist/css/adminlte.min.css">
    <!-- summernote -->
    <link rel="stylesheet" href="~/Themes/AdminLTE-3.0.4/plugins/summernote/summernote-bs4.css">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>


<body class="hold-transition sidebar-mini">
    <div class="wrapper">

        <!-- Content Wrapper. Contains page content -->
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Gelen Kutusu</h1>
                    </div>

                </div>
            </div><!-- /.container-fluid -->
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-md-3">
                    <a href="/CariPanel/YeniMesaj" class="btn btn-primary btn-block mb-3">Yeni Mesaj Oluştur</a>

                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">Dosyalar</h3>

                            <div class="card-tools">
                                <button type="button" class="btn btn-tool" data-card-widget="collapse">
                                    <i class="fas fa-minus"></i>
                                </button>
                            </div>
                        </div>
                        <div class="card-body p-0">
                            <ul class="nav nav-pills flex-column">
                                <li class="nav-item active">
                                    <a href="/CariPanel/GelenMesajlar" class="nav-link">
                                        <i class="fas fa-inbox"></i> Gelen Kutusu
                                        <span class="badge bg-primary float-right">@ViewBag.mesajSayisi</span>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="/CariPanel/GonderilenMesajlar" class="nav-link">
                                        <i class="far fa-envelope"></i> Gönderilenler
                                        <span class="badge bg-primary float-right">@ViewBag.gonderilenMesajSayisi</span>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="#" class="nav-link">
                                        <i class="far fa-file-alt"></i> Taslaklar
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="#" class="nav-link">
                                        <i class="fas fa-filter"></i> Gereksiz
                                        <span class="badge bg-warning float-right">65</span>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="#" class="nav-link">
                                        <i class="far fa-trash-alt"></i> Çöp Kutusu
                                    </a>
                                </li>
                            </ul>
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">Filtreler</h3>

                            <div class="card-tools">
                                <button type="button" class="btn btn-tool" data-card-widget="collapse">
                                    <i class="fas fa-minus"></i>
                                </button>
                            </div>
                        </div>
                        <div class="card-body p-0">
                            <ul class="nav nav-pills flex-column">
                                <li class="nav-item">
                                    <a href="#" class="nav-link">
                                        <i class="far fa-circle text-danger"></i>
                                        Önemli
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="#" class="nav-link">
                                        <i class="far fa-circle text-warning"></i> Promosyonlar
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="#" class="nav-link">
                                        <i class="far fa-circle text-primary"></i>
                                        Sosyal
                                    </a>
                                </li>
                            </ul>
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
                <!-- /.col -->
                <div class="col-md-9">
                    @using (Html.BeginForm("YeniMesaj", "CariPanel", FormMethod.Post))
                    {

                        <div class="card card-primary card-outline">
                            <div class="card-header">
                                <h3 class="card-title">Yeni Mesaj Gönderme Sayfası</h3>
                            </div>
                            <!-- /.card-header -->
                            <div class="card-body">
                                <div class="form-group">
                                    <input class="form-control" placeholder="Kime:" name="Alici">
                                </div>
                                <div class="form-group">
                                    <input class="form-control" placeholder="Konu:" name="Konu">
                                </div>
                                <div class="form-group">

                                    <textarea id="compose-textarea" class="form-control" style="height: 300px" name="MesajIcerik">
                                 </textarea>
                                </div>
                                <div class="form-group">
                                    <div class="btn btn-default btn-file">
                                        <i class="fas fa-paperclip"></i> Dosya Ekle
                                        <input type="file" name="attachment">
                                    </div>
                                    <p class="help-block">Max. 32MB</p>
                                </div>
                            </div>
                            <!-- /.card-body -->
                            <div class="card-footer">
                                <div class="float-right">

                                    <button type="submit" class="btn btn-primary"><i class="far fa-envelope"></i> Gönder</button>
                                </div>
                                <button type="reset" class="btn btn-default"><i class="fas fa-times"></i> Sil</button>
                            </div>
                            <!-- /.card-footer -->
                        </div>
                        <!-- /.card -->

                    }
                </div>

            </div>
            <!-- /.row -->
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
    <!-- ./wrapper -->
    <!-- jQuery -->

    <script src="~/Themes/AdminLTE-3.0.4/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="~/Themes/AdminLTE-3.0.4/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/Themes/AdminLTE-3.0.4/dist/js/adminlte.min.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="~/Themes/AdminLTE-3.0.4/dist/js/demo.js"></script>
    <!-- Summernote -->
    <script src="~/Themes/AdminLTE-3.0.4/plugins/summernote/summernote-bs4.min.js"></script>
    <!-- Page Script -->
    <script>
        $(function () {
            //Add text editor
            $('#YeniMesaj-textarea').summernote()
        })
    </script>




</body>
</html>