Models/Siniflar/Departman.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace MvcOnlineTicariOtomasyon.Models.Siniflar
{
    public class Departman
    {
        [Key]
        [Display(Name = "Departman ID")]
        public int DepartmanId { get; set; }

        [Display(Name = "Departman Ad")]
        [Column(TypeName = "Varchar")]
        [StringLength(30, ErrorMessage ="En fazla 30 karakter kullanabilirsiniz")]
        [Required(ErrorMessage ="Bu alan boş bırakılamaz")]
        public string DepartmanAd { get; set; }
        [Display(Name = "Departman Durum")]
        public bool Durum { get; set; }
        public ICollection<Personel> Personels { get; set; }
    }
}

Controllers/DepartmanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcOnlineTicariOtomasyon.Models.Siniflar;

namespace MvcOnlineTicariOtomasyon.Controllers
{[Authorize]
    public class DepartmanController : Controller
    {
        Context context = new Context();
        // GET: Departman
        public ActionResult Index()
        {
            var departmanlar = context.Departmans.Where(x=>x.Durum == true).ToList();
            return View(departmanlar);
        }


        
        [HttpGet]
        public ActionResult DepartmanEkle()
        {
            return View();
        }

        [HttpPost]  
        public ActionResult DepartmanEkle(Departman d)
        {
            if (!ModelState.IsValid)
            {
                return View("DepartmanEkle");
            }
            context.Departmans.Add(d);
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult DepartmanSil(int id)
        {
            var departman = context.Departmans.Find(id);
            context.Departmans.Remove(departman);
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult DepartmanGuncelle(int id)
        {
            var deger = context.Departmans.Find(id);
            return View(deger);
        }

        [HttpPost]
        public ActionResult DepartmanGuncelle(Departman d)
        {
            if (!ModelState.IsValid)
            {
                return View("DepartmanGuncelle");
            }
            var deger = context.Departmans.Find(d.DepartmanId);
            deger.DepartmanAd = d.DepartmanAd;
            deger.Durum = d.Durum;
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult DepartmanDetay(int id)
        {
            var personeller = context.Personels.Where(x => x.DepartmanId == id).ToList();
            var detay = context.Departmans.Where(x => x.DepartmanId == id).Select(y => y.DepartmanAd).FirstOrDefault();
            ViewBag.dpt = detay;
            return View(personeller);
        }

        public ActionResult DepartmanPersonelSatis(int id)
        {
            var satislar = context.SatisHarekets.Where(x => x.PersonelId == id).ToList();
            var isim = context.Personels.Where(x => x.PersonelId == id).Select(y => y.PersonelAd + " " +  y.PersonelSoyad).FirstOrDefault();
            ViewBag.p = isim;
            return View(satislar);
        }


    }
}

Views/Departman/DepartmanDetay.cshtml
@using MvcOnlineTicariOtomasyon.Models.Siniflar
@model List<Personel>
@{
    ViewBag.Title = "DepartmanDetay";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="~/style/style.css" rel="stylesheet" />
</head>
<body>

    <br />
    <h2>Departman Detay Sayfası</h2>
    <br />
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item active">Departman Adı : @ViewBag.dpt</li>
    </ol>
    <br />

    <table class="table table-hover">
        <tr>
            <td><h5>Personel ID</h5></td>
            <td><h5>Ad</h5></td>
            <td><h5>Soyad</h5></td>
            <td><h5>Görsel</h5></td>
            <td><h5>Satışlar</h5></td>
        </tr>
        @foreach (var p in Model)
        {
            <tr>
                <td>@p.PersonelId</td>
                <td>@p.PersonelAd</td>
                <td>@p.PersonelSoyad</td>
                <td>@p.PersonelGorsel</td>
                <td><a href="/Departman/DepartmanPersonelSatis/@p.PersonelId" class="btn btn-info">Satışlar</a></td>

            </tr>

        }
    </table>
</body>

Views/Departman/DepartmanEkle.cshtml
@model MvcOnlineTicariOtomasyon.Models.Siniflar.Departman
@{
    ViewBag.Title = "DepartmanEkle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="~/style/style.css" rel="stylesheet" />
</head>
<body>

    <br />
    <h2>Departman Ekle</h2>
    <br />

    <form class="form-group" method="post">
        @Html.LabelFor(x => x.DepartmanAd)
        <br />
        @Html.TextBoxFor(x => x.DepartmanAd, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.DepartmanAd, "", new { @style = "color:red" })
        <br />
        @Html.LabelFor(x => x.Durum)
        <br />
        @Html.TextBoxFor(x => x.Durum, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.Durum, "", new { @style = "color:red" })
        <br />
        <button class="button"><span>Kaydet</span></button>

    </form>
</body>

Views/Departman/DepartmanGuncelle.cshtml
@model MvcOnlineTicariOtomasyon.Models.Siniflar.Departman

@{
    ViewBag.Title = "DepartmanGuncelle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="~/style/style.css" rel="stylesheet" />
</head>
<body>

    <br />
    <h2>DepartmanGuncelle</h2>
    <br />
    @using (Html.BeginForm("DepartmanGuncelle", "Departman", FormMethod.Post))
    {
        @Html.HiddenFor(x => x.DepartmanId)
        <div class="form-group">
            @Html.LabelFor(x => x.DepartmanAd)
            @Html.TextBoxFor(x => x.DepartmanAd, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.DepartmanAd, "", new { @style = "color:red" })
            <br />
            @Html.LabelFor(x => x.Durum)
            @Html.TextBoxFor(x => x.Durum, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.Durum, "", new { @style = "color:red" })

        </div>
        <button class="button"><span>Güncelle</span></button>

    }
</body>

Views/Departman/DepartmanPersonelSatis.cshtml
@using MvcOnlineTicariOtomasyon.Models.Siniflar
@model List<SatisHareket>
@{
    ViewBag.Title = "DepartmanPersonelSatis";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br />
<h2>Personel Satis Sayfası</h2>
<br />
<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item active">Personel Adı : @ViewBag.p</li>
</ol>

<table class="table table-condensed">
    <tr>
        <td>Satış ID</td>
        <td>Ürün</td>
        <td>Cari</td>
        <td>Fiyat</td>
        <td>Adet</td>
        <td>Toplam</td>
        <td>Tarih</td>
        <td>Yazdır</td>
    </tr>
    @foreach (var s in Model)
    {
        <tr>
            <td>@s.SatisId</td>
            <td>@s.Urun.UrunAd</td>
            <td>@s.Cariler.CariAd @s.Cariler.CariSoyad</td>
            <td>@s.BirimFiyat</td>
            <td>@s.Adet</td>
            <td>@s.Tutar</td>
            <td>@s.Tarih</td>
            <td><a href="#" class="btn btn-primary">Yazdır</a></td>
        </tr>

    }
</table>
<br />

Views/Departman/Index.cshtml
@using MvcOnlineTicariOtomasyon.Models.Siniflar
@model List<Departman>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="~/style/style.css" rel="stylesheet" />
</head>
<body>

    <br />
    <h2>Departmanlar</h2>
    <br />

    <table class="table table-bordered" , style="margin-top:20px">
        <tr>
            <td><h5>ID</h5></td>
            <td><h5>Departman Adı</h5></td>
            <td><h5>Durum</h5></td>
            <td><h5>Sil</h5></td>
            <td><h5>Güncelle</h5></td>
            <td><h5>Detaylar</h5></td>
        </tr>
        @foreach (var d in Model)
        {
            <tr>
                <td>@d.DepartmanId</td>
                <td>@d.DepartmanAd</td>
                <td>@d.Durum</td>
                <td>
                    <a href="/Departman/DepartmanSil/@d.DepartmanId" class="btn btn-danger">Sil</a>
                </td>
                <td>
                    <a href="/Departman/DepartmanGuncelle/@d.DepartmanId" class="btn btn-success">Guncelle</a>
                </td>
                <td>
                    <a href="/Departman/DepartmanDetay/@d.DepartmanId" class="btn btn-info">Detaylar</a>
                </td>
            </tr>
        }


    </table>
    <a href="/Departman/DepartmanEkle" class="button"><span>Yeni Departman Ekle</span></a>
</body>