Controllers/GrafikController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using MvcOnlineTicariOtomasyon.Models.Siniflar;

namespace MvcOnlineTicariOtomasyon.Controllers
{
    public class GrafikController : Controller
    {
       
        // GET: Grafik
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Index2()
        {
            var grafik = new Chart(width: 500, height: 700);
            grafik.AddTitle("Kategori-Ürün Stok Sayısı");
            grafik.AddLegend("Stok");
            grafik.AddSeries("Degerler", xValue: new[] { "Mobilya", "Televizyon", "Elektronik", "Beyaz Eşya", },
                                        yValues: new[] { 500, 600, 700, 800 });
            grafik.Write();

            return File(grafik.ToWebImage().GetBytes(), "image/jpeg");
        }

        public ActionResult Index3()
        {
            ArrayList xvalue = new ArrayList();
            ArrayList yvalue = new ArrayList();
            Context context = new Context();
            var urunler = context.Uruns.ToList();
            urunler.ToList().ForEach(x => xvalue.Add(x.UrunAd));
            urunler.ToList().ForEach(y => yvalue.Add(y.Stok));

            var grafik = new Chart(width: 500, height: 600);
            grafik.AddTitle("Ürün Stok Grafiği");
            grafik.AddLegend("Stok");
            grafik.AddSeries("Stok Sayısı", xValue: xvalue, yValues: yvalue);
            grafik.Write();
            return File(grafik.ToWebImage().GetBytes(), "image/jpeg");


        }

        public ActionResult Index4()
        {
            return View();
        }

        public ActionResult VisualizationResult()
        {
            return Json(UrunListesi(), JsonRequestBehavior.AllowGet);
        }

        public List<Class2> UrunListesi()
        {
            List<Class2> stokSinif = new List<Class2>();

            stokSinif.Add(new Class2()
            {
                UrunAd = "Bilgisayar",
                UrunStok = 100
            });

            stokSinif.Add(new Class2()
            {
                UrunAd = "Beyaz Eşya",
                UrunStok = 200
            });

            stokSinif.Add(new Class2()
            {
                UrunAd = "Mobilya",
                UrunStok = 150
            });

            stokSinif.Add(new Class2()
            {
                UrunAd = "Elektronik",
                UrunStok = 145
            });

            stokSinif.Add(new Class2()
            {
                UrunAd = "Televizyon",
                UrunStok = 345
            });

            return stokSinif;
        }

        public ActionResult Index5()
        {
            return View();
        }

        public ActionResult VisualizationResult2()
        {
            return Json(UrunListesi2(), JsonRequestBehavior.AllowGet);
        }

        public List<Class3> UrunListesi2()
        {
            List<Class3> sinif3 = new List<Class3>();
            using (Context context = new Context())
            {
                sinif3 = context.Uruns.Select(x => new Class3
                {
                    UrunAD = x.UrunAd,
                    UrunSTOK = x.Stok
                }).ToList();
            }
            return sinif3;

        }
        public ActionResult Index6()
        {
            return View();
        }
        public ActionResult Index7()
        {
            return View();
        }
    }
}

Views/Grafik/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Index</h2>

@{ 

    var grafik = new Chart(width: 500, height: 500);
    grafik.AddTitle("Kategoriler ve ürünler");
    grafik.AddLegend("Degerler");

    grafik.AddSeries(name: "Veriler", xValue: new[] { "Beyaz Eşya", "Bilgisayar", "Küçük Ev Aletleri", "Mobilya" },
                                     yValues: new[] { 300, 400, 500, 600 });
    grafik.Write();
}

Views/Grafik/Index2.cshtml
@{
    ViewBag.Title = "Index2";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Index2</h2>

<div style="width:500px;height:700px">
    <img src="@Url.Action("Index2", "Grafik")"  />
</div>

Views/Grafik/Index3.cshtml
@{
    ViewBag.Title = "Index3";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Index3</h2>

<div style="width:500px;height:700px">
    <img src="@Url.Action("Index3", "Grafik")" />
</div>

Views/Grafik/Index4.cshtml
@{
    ViewBag.Title = "Index4";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}



<!DOCTYPE html>

<html lang="en">

<head>

    <title>Result Visualization</title>

    <script type="text/javascript" src="https://www.google.com/jsapi"></script>

    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>

    <script>

        $(document).ready(function () {

            $.ajax({

                type: "POST",

                dataType: "json",

                contentType: "application/json",

                url: '@Url.Action("VisualizationResult", "Grafik")',

                success: function (result) {

                    google.charts.load('current', {

                        'packages': ['corechart']

                    });

                    google.charts.setOnLoadCallback(function () {

                        drawChart(result);

                    });

                }

            });

        });



        function drawChart(result) {

            var data = new google.visualization.DataTable();

            data.addColumn('string', 'Name');

            data.addColumn('number', 'Stok Değeri');

            var dataArray = [];



            $.each(result, function (i, obj) {

                dataArray.push([obj.UrunAd, obj.UrunStok]);

            });

            data.addRows(dataArray);



            var columnChartOptions = {

                title: "Ürün-Stok Grafiği",

                width: 1000,

                height: 400,

                bar: { groupWidth: "20%" },

            };



            var columnChart = new google.visualization.ColumnChart(document

                .getElementById('columnchart_div'));



            columnChart.draw(data, columnChartOptions);

        }

    </script>

</head>

<body>

    <div id="columnchart_div"></div>
    @*<a href="@Url.Action("PieChart")" class="btn btn-danger">Pie Chart</a>

    <a href="@Url.Action("ColumnChart")" class="active btn btn-primary">Column Chart</a>

    <a href="@Url.Action("LineChart")" class="btn btn-warning">Line Chart</a>*@

</body>

</html>

Views/Grafik/Index5.cshtml
@{
    ViewBag.Title = "Index5";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<!DOCTYPE html>

<html lang="en">

<head>

    <title>Result Visualization</title>

    <script type="text/javascript" src="https://www.google.com/jsapi"></script>

    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>

    <script>

        $(document).ready(function () {

            $.ajax({

                type: "POST",

                dataType: "json",

                contentType: "application/json",

                url: '@Url.Action("VisualizationResult2", "Grafik")',

                success: function (result) {

                    google.charts.load('current', {

                        'packages': ['corechart']

                    });

                    google.charts.setOnLoadCallback(function () {

                        drawChart(result);

                    });

                }

            });

        });



        function drawChart(result) {

            var data = new google.visualization.DataTable();

            data.addColumn('string', 'Name');

            data.addColumn('number', 'Stok Değeri');

            var dataArray = [];



            $.each(result, function (i, obj) {

                dataArray.push([obj.UrunAD, obj.UrunSTOK]);

            });

            data.addRows(dataArray);



            var columnChartOptions = {

                title: "Ürün-Stok Grafiği",

                width: 1200,

                height: 800,

                bar: { groupWidth: "20%" },

            };



            var columnChart = new google.visualization.PieChart(document

                .getElementById('piechart_div'));



            columnChart.draw(data, columnChartOptions);

        }

    </script>

</head>

<body>

    <div id="piechart_div"></div>
    @*<a href="@Url.Action("PieChart")" class="btn btn-danger">Pie Chart</a>

        <a href="@Url.Action("ColumnChart")" class="active btn btn-primary">Column Chart</a>

        <a href="@Url.Action("LineChart")" class="btn btn-warning">Line Chart</a>*@

</body>

</html>

Views/Grafik/Index6.cshtml
@{
    ViewBag.Title = "Index6";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!DOCTYPE html>

<html lang="en">

<head>

    <title>Result Visualization</title>

    <script type="text/javascript" src="https://www.google.com/jsapi"></script>

    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>

    <script>

        $(document).ready(function () {

            $.ajax({

                type: "POST",

                dataType: "json",

                contentType: "application/json",

                url: '@Url.Action("VisualizationResult2", "Grafik")',

                success: function (result) {

                    google.charts.load('current', {

                        'packages': ['corechart']

                    });

                    google.charts.setOnLoadCallback(function () {

                        drawChart(result);

                    });

                }

            });

        });



        function drawChart(result) {

            var data = new google.visualization.DataTable();

            data.addColumn('string', 'Name');

            data.addColumn('number', 'Stok Değeri');

            var dataArray = [];



            $.each(result, function (i, obj) {

                dataArray.push([obj.UrunAD, obj.UrunSTOK]);

            });

            data.addRows(dataArray);



            var columnChartOptions = {

                title: "Ürün-Stok Grafiği",

                width: 1200,

                height: 800,

                bar: { groupWidth: "20%" },

            };



            var columnChart = new google.visualization.LineChart(document

                .getElementById('linechart_div'));



            columnChart.draw(data, columnChartOptions);

        }

    </script>

</head>

<body>

    <div id="linechart_div"></div>
    @*<a href="@Url.Action("PieChart")" class="btn btn-danger">Pie Chart</a>

        <a href="@Url.Action("ColumnChart")" class="active btn btn-primary">Column Chart</a>

        <a href="@Url.Action("LineChart")" class="btn btn-warning">Line Chart</a>*@

</body>

</html>

Views/Grafik/Index7.cshtml
@{
    ViewBag.Title = "Index7";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!DOCTYPE html>

<html lang="en">

<head>

    <title>Result Visualization</title>

    <script type="text/javascript" src="https://www.google.com/jsapi"></script>

    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>

    <script>

        $(document).ready(function () {

            $.ajax({

                type: "POST",

                dataType: "json",

                contentType: "application/json",

                url: '@Url.Action("VisualizationResult2", "Grafik")',

                success: function (result) {

                    google.charts.load('current', {

                        'packages': ['corechart']

                    });

                    google.charts.setOnLoadCallback(function () {

                        drawChart(result);

                    });

                }

            });

        });



        function drawChart(result) {

            var data = new google.visualization.DataTable();

            data.addColumn('string', 'Name');

            data.addColumn('number', 'Stok Değeri');

            var dataArray = [];



            $.each(result, function (i, obj) {

                dataArray.push([obj.UrunAD, obj.UrunSTOK]);

            });

            data.addRows(dataArray);



            var columnChartOptions = {

                title: "Ürün-Stok Grafiği",

                width: 1200,

                height: 800,

                bar: { groupWidth: "20%" },

            };



            var columnChart = new google.visualization.ColumnChart(document

                .getElementById('columnchart_div'));



            columnChart.draw(data, columnChartOptions);

        }

    </script>

</head>

<body>

    <div id="columnchart_div"></div>
    @*<a href="@Url.Action("PieChart")" class="btn btn-danger">Pie Chart</a>

        <a href="@Url.Action("ColumnChart")" class="active btn btn-primary">Column Chart</a>

        <a href="@Url.Action("LineChart")" class="btn btn-warning">Line Chart</a>*@

</body>

</html>